FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["bash", "-c", "python -m ml.train_model && uvicorn main:app --host 0.0.0.0 --port 8000"]